/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "xendfvgxucllfaazxksb"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhlbmRmdmd4dWNsbGZhYXp4a3NiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1MjI5ODMsImV4cCI6MjA3NzA5ODk4M30.cMntsXXx-l-v7txX1NyaDO-t0Ff-3G5dicIGJWWdhY8"